FROM node:14 as build

WORKDIR /client

COPY package.json .

COPY yarn.lock .

RUN yarn install

COPY . .

CMD ["yarn", "build"]

FROM nginx:stable-alpine

ENV NODE_ENV=development

COPY --from=build /client/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

