version: '3'
services:
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=testdb
    volumes:
      - mongo-db:/data/db
    ports:
      - 27017:27017
    networks:
      - dev
  mongodb-seed:
    build: ./data
    depends_on:
      - mongodb
    networks:
      - dev
  server:
    build:
      context: './server'
      dockerfile: 'Dockerfile'
    env_file:
      - .env
    depends_on:
      - mongodb
    ports:
      - 4000:4000
    volumes:
      - ./server:/server
      - /server/node_modules
    networks:
      - dev
  client:
    build:
      context: './client'
      dockerfile: 'Dockerfile'
    env_file:
      - .env
    depends_on:
      - mongodb
      - server
    ports:
      - 3000:3000
    volumes:
      - ./client:/client
      - /client/node_modules
    networks:
      - dev

volumes:
  mongo-db:

networks:
  dev:
    name: dev
    driver: bridge
