version: '3'
services:
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=testdb
    ports:
      - 27017:27017
    networks:
      - dev
  mongodb-seed:
    build:
      context: ./data
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    networks:
      - dev
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - PORT_SERVER=4000
      - API_PREFIX=api/v1/
    volumes:
      - ./server:/server
    depends_on:
      - mongodb
    ports:
      - 4000:4000
    networks:
      - dev
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    volumes:
      - ./client:/client
    depends_on:
      - mongodb
      - server
    ports:
      - 1234:1234
    networks:
      - dev
  scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    volumes:
      - ./scraper:/scraper
    stdin_open: true
    command: bash
    networks:
      - dev
  cypress:
    image: 'cypress/included:9.5.3'
    depends_on:
      - client
      - server
    environment:
      - CYPRESS_baseUrl=http://client:1234
    working_dir: /e2e
    volumes:
      - ./e2e:/e2e
    networks:
      - dev

networks:
  dev:
    name: dev
    driver: bridge
